services:
  - type: worker
    name: crypto-trading-bot
    env: python
    region: oregon
    plan: starter
    buildCommand: pip install -r requirements.txt
    startCommand: python main.py
    envVars:
      - key: PYTHON_VERSION
        value: 3.11.0
      - key: SIM_START_BALANCE_USD
        value: 100
